name: xmos-ai-tools-test-actions

on:
#   release:
#     types: [published]
#     tags:
#       - v*
  workflow_dispatch:
    inputs:
      version:
        description: "Provide a valid release tag version in the format vX.Y.Z"
        required: true

# Either we triggered a workflow providing a version or published a new release
# Save the tag version in an environment variable
env:
  TAG_VERSION: ${{ github.event.inputs.version == 0 && github.ref_name || github.event.inputs.version }}


jobs:
  macos-arm-release-wheel:
    name: Build release wheels for macOS arm64
    runs-on: macos-11
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-arm-${{ env.cache-name }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ env.TAG_VERSION }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build macOS arm wheels
        env:
          XMOS_AI_TOOLS_RELEASE_VERSION: ${{ env.TAG_VERSION }}
        shell: bash
        run: |
          python --version
          python -m pip install wheel setuptools numpy six --no-cache-dir
          
          cd third_party/lib_tflite_micro
          make build
                    
          cd ${{ env.GITHUB_WORKSPACE }}/experimental/xformer
          bazelisk build //:xcore-opt --copt=-fvisibility=hidden --copt=-mmacosx-version-min=11.0 --linkopt=-mmacosx-version-min=11.0 --linkopt=-dead_strip
          
          cd python
          python setup.py bdist_wheel --plat-name macosx_11_0_arm64
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-arm-wheels
          path: experimental/xformer/python/dist



  publish-wheels:
    name: Publish wheels to TestPyPi
    if: ${{ always() }}
    needs: [macos-arm-release-wheel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: macOS-arm-wheels
          path: macOS-arm-wheels
        if: ${{ needs.macos-arm-release-wheel.result == 'success' }}
      - run: |
          set -x
          mkdir -p dist
          cp macOS-arm-wheels/*.whl dist/ || true
          ls -la dist/
          sha256sum dist/*.whl
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
