name: xmos-ai-tools-test-actions

on:
  release:
    types: [published]
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: "Provide release tag version in the format vX.Y.Z"
        required: true

# Either we triggered a workflow providing a version or published a new release
# Save the tag version in an environment variable
env:
  TAG_VERSION: ${{ github.event.inputs.version == 0 && github.ref_name || github.event.inputs.version }}

jobs:     
  manylinux-release-wheel:
    name: Build release wheels for manylinux2010
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ env.TAG_VERSION }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build manylinux2010 wheels
        run: |
          #mkdir -p experimental/xformer/bazel-bin
          #touch experimental/xformer/bazel-bin/xcore-opt
          #docker run -v ${PWD}:/ai_tools -w /ai_tools/experimental/xformer/python \
          #  tensorflow/build:latest-python${{ matrix.python-version }} \
          # python setup.py bdist_wheel

          docker run -e XMOS_AI_TOOLS_RELEASE_VERSION=${{ env.TAG_VERSION }} \
            -v ${PWD}:/ai_tools -w /ai_tools \
            tensorflow/build:latest-python${{ matrix.python-version }} \
            .github/scripts/build_linux_wheel.sh
          
          sudo apt-get -y -qq install patchelf --no-install-recommends
          python -m pip install auditwheel --no-cache-dir
          cd experimental/xformer/python
          #python setup.py bdist_wheel

          for f in dist/*.whl; do
            auditwheel repair --plat manylinux2010_x86_64 $f
          done
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-wheels
          path: experimental/xformer/python/dist
          
  publish-wheels:
    name: Publish wheels to TestPyPi
    if: ${{ always() }}
    needs: [manylinux-release-wheel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Linux-wheels
          path: Linux-wheels
        if: ${{ needs.manylinux-release-wheel.result == 'success' }}
      - run: |
          set -x
          mkdir -p dist
          cp Linux-wheels/*.whl dist/ || true
          ls -la dist/
          sha256sum dist/*.whl
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
