name: xmos-ai-tools-test-actions

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Provide a valid release tag version in the format vX.Y.Z"
        required: true

jobs:
  macos-arm-release-wheel:
    name: Build release wheels for macOS arm64
    runs-on: macos-11
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-arm-${{ env.cache-name }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build macOS arm wheels
        shell: bash
        run: |
          python --version
          python -m pip install wheel setuptools setuptools-scm numpy six --no-cache-dir
          
          cd third_party/lib_tflite_micro
          make build
          
          file /Users/runner/work/ai_tools/ai_tools/third_party/lib_tflite_micro/xtflm_interpreter/xtflm_interpreter/libs/macos/xtflm_python.1.0.1.dylib
                    
          #cd ../../experimental/xformer
          #bazelisk build //:xcore-opt --copt=-fvisibility=hidden --copt=-mmacosx-version-min=11.0 --linkopt=-mmacosx-version-min=11.0 --linkopt=-dead_strip
          
          #cd python
          #python setup.py bdist_wheel --plat-name macosx_11_0_arm64
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-arm-wheels
          path: experimental/xformer/python/dist



  publish-wheels:
    name: Publish wheels to TestPyPi
    if: ${{ always() }}
    needs: [macos-arm-release-wheel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: macOS-wheels
          path: macOS-wheels
        if: ${{ needs.macos-release-wheel.result == 'success' }}
      - uses: actions/download-artifact@v2
        with:
          name: macOS-arm-wheels
          path: macOS-arm-wheels
        if: ${{ needs.macos-arm-release-wheel.result == 'success' }}
      - uses: actions/download-artifact@v2
        with:
          name: Linux-wheels
          path: Linux-wheels
        if: ${{ needs.manylinux-release-wheel.result == 'success' }}
      - run: |
          set -x
          mkdir -p dist
          cp macOS-wheels/*.whl dist/ || true
          cp macOS-arm-wheels/*.whl dist/ || true
          cp Linux-wheels/*.whl dist/ || true
          ls -la dist/
          sha256sum dist/*.whl
      - name: Publish packages to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
