name: xmos-ai-tools-test-actions

on:
  push:
    branches:
      - develop

jobs:
  manylinux-release-wheel:
    name: Build release wheels for manylinux2010
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: set env
        run: echo "TAG_VERSION=`echo $(git describe --tags --abbrev=0)`.dev$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build manylinux2010 wheels
        # The XMOS_AI_TOOLS_RELEASE_VERSION var is passed via docker to the
        # python setup.py script to add the version info for the wheel file.
        #
        # auditwheel requires patchelf and repairs the created wheel file to 
        # be compatible for manylinux.
        run: |
          set -x
          echo ${{ env.TAG_VERSION }}

          python -m pip install wheel setuptools setuptools-scm numpy six --no-cache-dir
          cd experimental/xformer/python
          python setup.py --version
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-wheels
          # auditwheel creates the output wheel in the wheelhouse folder
          path: experimental/xformer/python/wheelhouse



  publish-wheels:
    name: Publish wheels to TestPyPi
    if: ${{ always() }}
    needs: [manylinux-release-wheel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: macOS-wheels
          path: macOS-wheels
        if: ${{ needs.macos-release-wheel.result == 'success' }}
      - uses: actions/download-artifact@v2
        with:
          name: macOS-arm-wheels
          path: macOS-arm-wheels
        if: ${{ needs.macos-arm-release-wheel.result == 'success' }}
      - uses: actions/download-artifact@v2
        with:
          name: Linux-wheels
          path: Linux-wheels
        if: ${{ needs.manylinux-release-wheel.result == 'success' }}
      - run: |
          set -x
          mkdir -p dist
          cp macOS-wheels/*.whl dist/ || true
          cp macOS-arm-wheels/*.whl dist/ || true
          cp Linux-wheels/*.whl dist/ || true
          ls -la dist/
          sha256sum dist/*.whl
      - name: Publish packages to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
